/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra novo usuário e cria carteira inicial */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Usuário registrado com sucesso */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegisterResponse"];
                    };
                };
                /** @description Dados inválidos */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Email já cadastrado */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConflictError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentica usuário (placeholder - usar Clerk OAuth em produção) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email?: string;
                        /** @example Senha */
                        password?: string;
                    };
                };
            };
            responses: {
                /** @description Token retornado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Credenciais inválidas */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renova access token usando refresh token (placeholder) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken?: string;
                    };
                };
            };
            responses: {
                /** @description Token renovado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retorna dados do usuário autenticado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dados do usuário */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Não autenticado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description Usuário não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Faz logout e invalida session (gerenciado pelo Clerk) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout realizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogoutResponse"];
                    };
                };
                /** @description Não autenticado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bets/event/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista apostas de um evento */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de apostas do evento */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BetListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Coloca uma nova aposta */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlaceBetRequest"];
                };
            };
            responses: {
                /** @description Aposta criada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BetResponse"];
                    };
                };
                /** @description Dados inválidos */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bets/{betId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancela uma aposta pendente */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    betId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CancelBetRequest"];
                };
            };
            responses: {
                /** @description Aposta cancelada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BetResponse"];
                    };
                };
                /** @description Não pode cancelar */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bets/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista apostas do usuário autenticado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de apostas do usuário */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BetListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retorna dados completos do usuário autenticado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Usuário encontrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Não autenticado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description Usuário não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza perfil do usuário autenticado */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example João */
                        firstName?: string;
                        /** @example Silva */
                        lastName?: string;
                        /** @example Apaixonado por apostas desportivas */
                        bio?: string;
                    };
                };
            };
            responses: {
                /** @description Perfil atualizado com sucesso */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Dados inválidos */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Não autenticado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/users/me/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Altera email do usuário autenticado */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example newemail@example.com
                         */
                        email: string;
                        /** @description Código de verificação enviado por email */
                        verificationCode?: string;
                    };
                };
            };
            responses: {
                /** @description Email alterado com sucesso */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Dados inválidos */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Não autenticado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description Email já cadastrado */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConflictError"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/wallets/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retorna a carteira do usuário autenticado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Carteira encontrada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WalletResponse"];
                    };
                };
                /** @description Não autenticado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
                /** @description Carteira não encontrada */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallets/deposit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Realiza depósito na carteira do usuário */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 100 */
                        amount: number;
                        /**
                         * @example BRL
                         * @enum {string}
                         */
                        currency: "BRL" | "USD" | "EUR";
                        /** @example Depósito via cartão de crédito */
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Depósito realizado com sucesso */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WalletResponse"];
                    };
                };
                /** @description Dados inválidos */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Não autenticado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallets/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Realiza saque da carteira do usuário */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 50 */
                        amount: number;
                        /**
                         * @example BRL
                         * @enum {string}
                         */
                        currency: "BRL" | "USD" | "EUR";
                        /** @example Saque para conta bancária */
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Saque realizado com sucesso */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WalletResponse"];
                    };
                };
                /** @description Dados inválidos ou saldo insuficiente */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Não autenticado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallets/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retorna histórico de transações da carteira */
        get: {
            parameters: {
                query?: {
                    /** @description Número de transações a retornar */
                    limit?: number;
                    /** @description Deslocamento para paginação */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Histórico retornado com sucesso */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionHistory"];
                    };
                };
                /** @description Não autenticado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /**
             * Format: uuid
             * @example cadaeb28-c7f7-425b-91f7-73a27141ae49
             */
            id: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example joaosilva */
            username: string;
            /** @example João */
            firstName?: string;
            /** @example Silva */
            lastName?: string;
            /**
             * @example ACTIVE
             * @enum {string}
             */
            status: "PENDING_VERIFICATION" | "ACTIVE" | "SUSPENDED";
            /**
             * Format: date-time
             * @example 2025-11-14T23:20:42.778Z
             */
            createdAt: string;
        };
        Wallet: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            balance?: {
                /** @example 1000 */
                amount?: number;
                /** @example BRL */
                currency?: string;
            };
            /** Format: date-time */
            createdAt?: string;
        };
        /**
         * @example {
         *       "success": true,
         *       "data": {
         *         "id": "11111111-1111-1111-1111-111111111111",
         *         "userId": "cadaeb28-c7f7-425b-91f7-73a27141ae49",
         *         "balance": {
         *           "amount": 1000,
         *           "currency": "BRL"
         *         },
         *         "createdAt": "2025-11-14T23:20:42.778Z"
         *       },
         *       "meta": {
         *         "timestamp": "2025-11-15T15:18:29.622Z"
         *       }
         *     }
         */
        WalletResponse: {
            success?: boolean;
            data?: components["schemas"]["Wallet"];
            meta?: {
                /** Format: date-time */
                timestamp?: string;
            };
        };
        RegisterRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /**
             * Format: password
             * @example SecurePass@123
             */
            password: string;
            /** @example João */
            firstName: string;
            /** @example Silva */
            lastName: string;
            /** @example joaosilva */
            username: string;
        };
        /**
         * @example {
         *       "success": true,
         *       "data": {
         *         "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.example",
         *         "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.example",
         *         "user": {
         *           "id": "cadaeb28-c7f7-425b-91f7-73a27141ae49",
         *           "email": "user@example.com",
         *           "username": "joaosilva",
         *           "firstName": "João",
         *           "lastName": "Silva",
         *           "status": "PENDING_VERIFICATION",
         *           "createdAt": "2025-11-14T23:20:42.778Z"
         *         }
         *       },
         *       "meta": {
         *         "timestamp": "2025-11-15T15:18:29.622Z"
         *       }
         *     }
         */
        AuthResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                accessToken?: string;
                /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                refreshToken?: string;
                user?: components["schemas"]["User"];
            };
            meta?: {
                /** Format: date-time */
                timestamp?: string;
            };
        };
        /**
         * @example {
         *       "success": false,
         *       "error": {
         *         "code": "BAD_REQUEST",
         *         "message": "Dados inválidos",
         *         "details": {
         *           "username": "Invalid input: expected string"
         *         }
         *       },
         *       "meta": {
         *         "timestamp": "2025-11-15T15:18:29.623Z"
         *       }
         *     }
         */
        ErrorResponse: {
            /** @example false */
            success?: boolean;
            error?: {
                /** @example BAD_REQUEST */
                code?: string;
                /** @example Dados inválidos */
                message?: string;
                details?: components["schemas"]["ValidationError"] | Record<string, never>;
            };
            meta?: {
                /** Format: date-time */
                timestamp?: string;
            };
        };
        /**
         * @example {
         *       "success": true,
         *       "data": {
         *         "message": "Usuário registrado com sucesso",
         *         "user": {
         *           "id": "cadaeb28-c7f7-425b-91f7-73a27141ae49",
         *           "email": "user@example.com",
         *           "username": "joaosilva",
         *           "status": "PENDING_VERIFICATION",
         *           "createdAt": "2025-11-14T23:20:42.778Z"
         *         }
         *       },
         *       "meta": {
         *         "timestamp": "2025-11-14T23:20:42.778Z"
         *       }
         *     }
         */
        RegisterResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                /** @example Usuário registrado com sucesso */
                message?: string;
                user?: components["schemas"]["User"];
            };
            meta?: {
                /** Format: date-time */
                timestamp?: string;
            };
        };
        /**
         * @example {
         *       "success": true,
         *       "data": {
         *         "id": "cadaeb28-c7f7-425b-91f7-73a27141ae49",
         *         "email": "user@example.com",
         *         "username": "joaosilva",
         *         "firstName": "João",
         *         "lastName": "Silva",
         *         "status": "ACTIVE",
         *         "createdAt": "2025-11-14T23:20:42.778Z"
         *       },
         *       "meta": {
         *         "timestamp": "2025-11-14T23:21:06.343Z"
         *       }
         *     }
         */
        MeResponse: {
            /** @example true */
            success?: boolean;
            data?: components["schemas"]["User"];
            meta?: {
                /** Format: date-time */
                timestamp?: string;
            };
        };
        /**
         * @example {
         *       "success": true,
         *       "data": {
         *         "message": "Logout realizado com sucesso"
         *       },
         *       "meta": {
         *         "timestamp": "2025-11-14T23:22:00.000Z"
         *       }
         *     }
         */
        LogoutResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                /** @example Logout realizado com sucesso */
                message?: string;
            };
            meta?: {
                /** Format: date-time */
                timestamp?: string;
            };
        };
        /**
         * @example {
         *       "success": false,
         *       "error": {
         *         "code": "CONFLICT",
         *         "message": "Email já cadastrado"
         *       },
         *       "meta": {
         *         "timestamp": "2025-11-14T23:20:00.000Z"
         *       }
         *     }
         */
        ConflictError: {
            /** @example false */
            success?: boolean;
            error?: {
                /** @example CONFLICT */
                code?: string;
                /** @example Email já cadastrado */
                message?: string;
            };
            meta?: {
                /** Format: date-time */
                timestamp?: string;
            };
        };
        /**
         * @description Detalhes de validação por campo
         * @example {
         *       "email": "Formato de email inválido",
         *       "username": "Tamanho mínimo: 3"
         *     }
         */
        ValidationError: {
            [key: string]: string;
        };
        AppError: {
            /** @example BAD_REQUEST */
            code?: string;
            /** @example Mensagem de erro */
            message?: string;
            details?: components["schemas"]["ValidationError"] | Record<string, never>;
        };
        Transaction: {
            /** Format: uuid */
            id?: string;
            /** @example DEPOSIT */
            type?: string;
            /** @example 100.5 */
            amount?: number;
            /** @example BRL */
            currency?: string;
            /** @example Depósito via cartão */
            description?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        TransactionHistory: {
            transactions?: components["schemas"]["Transaction"][];
            /** @example 42 */
            total?: number;
        };
        /**
         * @example {
         *       "success": false,
         *       "error": {
         *         "code": "UNAUTHORIZED",
         *         "message": "Autenticação requerida"
         *       },
         *       "meta": {
         *         "timestamp": "2025-11-14T23:21:00.000Z"
         *       }
         *     }
         */
        UnauthorizedError: {
            /** @example false */
            success?: boolean;
            error?: {
                /** @example UNAUTHORIZED */
                code?: string;
                /** @example Autenticação requerida */
                message?: string;
            };
            meta?: {
                /** Format: date-time */
                timestamp?: string;
            };
        };
        PlaceBetRequest: {
            /**
             * Format: uuid
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            eventId: string;
            /** @example market-123 */
            marketId: string;
            /** @example odd-456 */
            oddId: string;
            /** @example 50 */
            amount: number;
            /**
             * @example SINGLE
             * @enum {string}
             */
            type?: "SINGLE" | "MULTIPLE";
            /**
             * @example BRL
             * @enum {string}
             */
            currency?: "BRL" | "USD" | "EUR";
        };
        CancelBetRequest: {
            /**
             * Format: uuid
             * @example 7d9f6c2b-1b2a-4a8b-9c0d-123456789abc
             */
            betId: string;
            /** @example Erro no mercado */
            reason?: string;
        };
        BetResponse: {
            /**
             * Format: uuid
             * @example 7d9f6c2b-1b2a-4a8b-9c0d-123456789abc
             */
            id?: string;
            /**
             * Format: uuid
             * @example cadaeb28-c7f7-425b-91f7-73a27141ae49
             */
            userId?: string;
            /**
             * Format: uuid
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            eventId?: string;
            /** @example market-123 */
            marketId?: string;
            /** @example 50 */
            amount?: number;
            /** @example 1.85 */
            odds?: number;
            /** @example 92.5 */
            potentialReturn?: number;
            /**
             * @example PENDING
             * @enum {string}
             */
            status?: "PENDING" | "WON" | "LOST" | "CANCELED";
            /** @example SINGLE */
            type?: string;
            /**
             * Format: date-time
             * @example 2025-11-14T23:30:00.000Z
             */
            createdAt?: string;
            /** Format: date-time */
            resolvedAt?: string | null;
            cancellationReason?: string | null;
        };
        BetListResponse: {
            bets?: components["schemas"]["BetResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
